defmodule Google.Ads.Googleads.V2.Errors.SettingErrorEnum do
  @moduledoc false
  use Protobuf, syntax: :proto3

  @type t :: %__MODULE__{}
  defstruct []
end

defmodule Google.Ads.Googleads.V2.Errors.SettingErrorEnum.SettingError do
  @moduledoc false
  use Protobuf, enum: true, syntax: :proto3

  field(:UNSPECIFIED, 0)
  field(:UNKNOWN, 1)
  field(:SETTING_TYPE_IS_NOT_AVAILABLE, 3)
  field(:SETTING_TYPE_IS_NOT_COMPATIBLE_WITH_CAMPAIGN, 4)
  field(:TARGETING_SETTING_CONTAINS_INVALID_CRITERION_TYPE_GROUP, 5)
  field(:TARGETING_SETTING_DEMOGRAPHIC_CRITERION_TYPE_GROUPS_MUST_BE_SET_TO_TARGET_ALL, 6)

  field(
    :TARGETING_SETTING_CANNOT_CHANGE_TARGET_ALL_TO_FALSE_FOR_DEMOGRAPHIC_CRITERION_TYPE_GROUP,
    7
  )

  field(:DYNAMIC_SEARCH_ADS_SETTING_AT_LEAST_ONE_FEED_ID_MUST_BE_PRESENT, 8)
  field(:DYNAMIC_SEARCH_ADS_SETTING_CONTAINS_INVALID_DOMAIN_NAME, 9)
  field(:DYNAMIC_SEARCH_ADS_SETTING_CONTAINS_SUBDOMAIN_NAME, 10)
  field(:DYNAMIC_SEARCH_ADS_SETTING_CONTAINS_INVALID_LANGUAGE_CODE, 11)
  field(:TARGET_ALL_IS_NOT_ALLOWED_FOR_PLACEMENT_IN_SEARCH_CAMPAIGN, 12)
  field(:UNIVERSAL_APP_CAMPAIGN_SETTING_DUPLICATE_DESCRIPTION, 13)
  field(:UNIVERSAL_APP_CAMPAIGN_SETTING_DESCRIPTION_LINE_WIDTH_TOO_LONG, 14)
  field(:UNIVERSAL_APP_CAMPAIGN_SETTING_APP_ID_CANNOT_BE_MODIFIED, 15)
  field(:TOO_MANY_YOUTUBE_MEDIA_IDS_IN_UNIVERSAL_APP_CAMPAIGN, 16)
  field(:TOO_MANY_IMAGE_MEDIA_IDS_IN_UNIVERSAL_APP_CAMPAIGN, 17)
  field(:MEDIA_INCOMPATIBLE_FOR_UNIVERSAL_APP_CAMPAIGN, 18)
  field(:TOO_MANY_EXCLAMATION_MARKS, 19)
end
